package fc.coupon.core.exception;

public enum ErrorCode {
    INVALID_COUPON_ISSUE_QUANTITY,
    INVALID_COUPON_ISSUE_DATE,
    COUPON_NOT_EXIST,
    DUPLICATED_COUPON_ISSUE,
    FAIL_COUPON_ISSUE_REQUEST
}
